version: "1"

services:

  url:
    image: url:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
      - redis
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    ports:
      - "8080:8080"
    restart: unless-stopped

  postgres_db:
    image: postgres:11.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=mypass
      - REDIS_PORT=6379
      - REDIS_DATABASES=0